### ISSUE TITLE
disabled state

### ISSUE THREAD

**Issue by ryuken** [brownieboy/react-bootstrap-slider#52]
i don't know it this is desired but its weird

the disabled state works correctly (becomes gray) but instead of a circle the drag icon is a square
i think it should be a gray circle

**Comment by brownieboy** [comment]
Here's how the cursor icon looks on the disabled control on my demo code:
![disabled_screenshot](https://user-images.githubusercontent.com/1781909/53293311-9b2eed00-3825-11e9-8c06-79c7fe1e6ce7.jpg)

Here's the CSS that appears to be setting it:
```css
.slider.slider-disabled .slider-track {
    background-image: -webkit-linear-gradient(top, #e5e5e5 0%, #e9e9e9 100%);
    background-image: linear-gradient(to bottom, #e5e5e5 0%, #e9e9e9 100%);
    background-repeat: repeat-x;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffe5e5e5', endColorstr='#ffe9e9e9', GradientType=0);
    cursor: not-allowed;
}
```

So, it's the **not-allowed** cursor style that's being set.
